In [1]:
import pandas as pd

In this we are going to know what Hierarchical indexing is - (also known as multi-indexing)

In [2]:
df = pd.read_csv("Pokemon.csv")
df

,#,Name,Type 1,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
0,1,Bulbasaur,Grass,Poison,318,45,49,49,65,65,45,1,False
1,2,Ivysaur,Grass,Poison,405,60,62,63,80,80,60,1,False
2,3,Venusaur,Grass,Poison,525,80,82,83,100,100,80,1,False
3,3,VenusaurMega Venusaur,Grass,Poison,625,80,100,123,122,120,80,1,False
4,4,Charmander,Fire,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
795,719,Diancie,Rock,Fairy,600,50,100,150,100,150,50,6,True
796,719,DiancieMega Diancie,Rock,Fairy,700,50,160,110,160,110,110,6,True
797,720,HoopaHoopa Confined,Psychic,Ghost,600,80,110,60,150,130,70,6,True
798,720,HoopaHoopa Unbound,Psychic,Dark,680,80,160,60,170,130,80,6,True
799,721,Volcanion,Fire,Water,600,80,110,120,130,90,70,6,True

In Pandas we can create multi-index by passing in a list of columns names into a `set_index()`

In [3]:
# Lets set Name and Type 1 column as index
df.set_index(["Name", "Type 1"], inplace=True)
df

,,#,Type 2,Total,HP,Attack,Defense,Sp. Atk,Sp. Def,Speed,Generation,Legendary
Name,Type 1,,,,,,,,,,,
Bulbasaur,Grass,1,Poison,318,45,49,49,65,65,45,1,False
Ivysaur,Grass,2,Poison,405,60,62,63,80,80,60,1,False
Venusaur,Grass,3,Poison,525,80,82,83,100,100,80,1,False
VenusaurMega Venusaur,Grass,3,Poison,625,80,100,123,122,120,80,1,False
Charmander,Fire,4,NaN,309,39,52,43,60,50,65,1,False
...,...,...,...,...,...,...,...,...,...,...,...,...
Diancie,Rock,719,Fairy,600,50,100,150,100,150,50,6,True
DiancieMega Diancie,Rock,719,Fairy,700,50,160,110,160,110,110,6,True
HoopaHoopa Confined,Psychic,720,Ghost,600,80,110,60,150,130,70,6,True
HoopaHoopa Unbound,Psychic,720,Dark,680,80,160,60,170,130,80,6,True
Volcanion,Fire,721,Water,600,80,110,120,130,90,70,6,True

In [5]:
# lets get the index
df.index
# Oh! we got multi index - in a tuple - means first element we can access First index name 
# with 0 and second with 1 and so on..

MultiIndex([(                'Bulbasaur',   'Grass'),
            (                  'Ivysaur',   'Grass'),
            (                 'Venusaur',   'Grass'),
            (    'VenusaurMega Venusaur',   'Grass'),
            (               'Charmander',    'Fire'),
            (               'Charmeleon',    'Fire'),
            (                'Charizard',    'Fire'),
            ('CharizardMega Charizard X',    'Fire'),
            ('CharizardMega Charizard Y',    'Fire'),
            (                 'Squirtle',   'Water'),
            ...
            (                   'Noibat',  'Flying'),
            (                  'Noivern',  'Flying'),
            (                  'Xerneas',   'Fairy'),
            (                  'Yveltal',    'Dark'),
            (         'Zygarde50% Forme',  'Dragon'),
            (                  'Diancie',    'Rock'),
            (      'DiancieMega Diancie',    'Rock'),
            (      'HoopaHoopa Confined', 'Psychic'),
            (       'HoopaHoopa Unbound', 'Psychic'),
            (                'Volcanion',    'Fire')],
           names=['Name', 'Type 1'], length=800)

lets get the Name index back - with `get_level_values()` -  this helps us to specify which index you want to get back

In [6]:
df.index.get_level_values(1) # This way we get the Name index list

Index(['Grass', 'Grass', 'Grass', 'Grass', 'Fire', 'Fire', 'Fire', 'Fire',
       'Fire', 'Water',
       ...
       'Flying', 'Flying', 'Fairy', 'Dark', 'Dragon', 'Rock', 'Rock',
       'Psychic', 'Psychic', 'Fire'],
      dtype='object', name='Type 1', length=800)

We can also swap the levels using `swaplevel()`

In [7]:
df = df.swaplevel()
df # Now, Type 1 is first value of index and Name column is 2nd value.

                                 #  Type 2  Total  HP  Attack  Defense  \
Type 1  Name
Grass   Bulbasaur                1  Poison    318  45      49       49
        Ivysaur                  2  Poison    405  60      62       63
        Venusaur                 3  Poison    525  80      82       83
        VenusaurMega Venusaur    3  Poison    625  80     100      123
Fire    Charmander               4     NaN    309  39      52       43
...                            ...     ...    ...  ..     ...      ...
Rock    Diancie                719   Fairy    600  50     100      150
        DiancieMega Diancie    719   Fairy    700  50     160      110
Psychic HoopaHoopa Confined    720   Ghost    600  80     110       60
        HoopaHoopa Unbound     720    Dark    680  80     160       60
Fire    Volcanion              721   Water    600  80     110      120

                               Sp. Atk  Sp. Def  Speed  Generation  Legendary
Type 1  Name
Grass   Bulbasaur                   65       65     45           1      False
        Ivysaur                     80       80     60           1      False
        Venusaur                   100      100     80           1      False
        VenusaurMega Venusaur      122      120     80           1      False
Fire    Charmander                  60       50     65           1      False
...                                ...      ...    ...         ...        ...
Rock    Diancie                    100      150     50           6       True
        DiancieMega Diancie        160      110    110           6       True
Psychic HoopaHoopa Confined        150      130     70           6       True
        HoopaHoopa Unbound         170      130     80           6       True
Fire    Volcanion                  130       90     70           6       True

[800 rows x 11 columns]